{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chengis.fullname" . }}-secrets
  labels:
    {{- include "chengis.labels" . | nindent 4 }}
type: Opaque
stringData:
  CHENGIS_DATABASE_PASSWORD: {{ .Values.database.password | quote }}
  CHENGIS_AUTH_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  CHENGIS_AUTH_SESSION_SECRET: {{ .Values.auth.sessionSecret | quote }}
  CHENGIS_SECRETS_MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  CHENGIS_DISTRIBUTED_AUTH_TOKEN: {{ .Values.distributed.authToken | quote }}
{{- end }}
